name: Thomas Bateller
favicon: null
layout_spectrum: 0.7450248005334288
typography_spectrum: 0.6395625569857657
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4155912841670215
  lightness: 0.23442194540984929
  saturation: 0.7209390932694077
  rhythmicContrast: 0.4685677634552121
purpose: []
